name: hello_firebase
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.5+2
  provider: ^4.0.4
  cupertino_icons: ^0.1.2
  flutter_spinkit: "^4.1.2"

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: " assets/icon/icono.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image_buttons/Jugadores.png
    - assets/image_buttons/Torneos.png
    - assets/icon.png

